### ISSUE TITLE
Got an error on install into wordpress 4.5.2

### ISSUE THREAD

**Issue by esobczak1970** [justincwatt/wp-sql-executioner#2]
Hope you'll update this, hard to believe there aren't other plugins that allow you to do simple sql queries.

**Comment by anou** [comment]
I don't know if it's the same issue but on activation, I get a fatal error :
`Call to undefined function mysql_connect()`

I've changed to use MYSQLI in sql-executioner.php

But it could be great to have the choice to choose between MYSQL or MYSQLI

**Comment by justincwatt** [comment]
This was a PHP 7 compatibility error, not a WordPress version compatibility error (as @anou pointed to: PHP 7 removed the old `mysql_*` functions, which I'd used here out of habit). Fixed in 3b5eeaad8f35d9e0973ce795df05ca9e22923948. [Upgrade to v1.3+ of the plugin](https://wordpress.org/plugins/sql-executioner/) if you're webhost is running PHP 7 and all should be well.
